# -*- coding: utf-8 -*-
"""Data_cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1NYRPdiyIiYoQSTgHIYOthwf1VKM2dF
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# data_cleaning.py
import pandas as pd
import numpy as np
import re
import os

DATA_DIR = "/content/drive/MyDrive/Capstone_Project/Data/preprocess"
OUT_DIR = f"{DATA_DIR}/cleaned"
os.makedirs(OUT_DIR, exist_ok=True)

menu_csv = f"{DATA_DIR}/menu-processing/preprocessed-data/menu preprocess.csv"
pdf_csv = f"{DATA_DIR}/pos-processing/preprocessed-data/pdf preprocess.csv"
school_csv = f"{DATA_DIR}/school-processing/preprocessed-data/schools preprocess.csv"

# --- helper functions ---
def clean_text(val):
    """Standardize strings: lowercase, strip, remove punctuation/double spaces"""
    if pd.isna(val):
        return ""
    s = str(val).strip().lower()
    s = re.sub(r"[^\w\s]", "", s)   # remove punctuation
    s = re.sub(r"\s+", " ", s)      # collapse spaces
    return s

def clean_menu(df):
    """Cleaning rules for menu data"""
    df = df.copy()
    if "Item_Name" in df:
        df["Item_Name"] = df["Item_Name"].apply(clean_text)
    if "Category" in df:
        df["Category"] = df["Category"].apply(clean_text)
    # remove duplicates
    df = df.drop_duplicates().reset_index(drop=True)
    return df

def clean_pdf(df):
    """Cleaning rules for POS/pdf data"""
    df = df.copy()
    if "Item_Name" in df:
        df["Item_Name"] = df["Item_Name"].apply(clean_text)
    if "Sold_Total" in df:
        df["Sold_Total"] = pd.to_numeric(df["Sold_Total"], errors="coerce").fillna(0).astype(int)
    if "Date" in df:
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    df = df.drop_duplicates().reset_index(drop=True)
    return df

def clean_schools(df):
    """Cleaning rules for schools data"""
    df = df.copy()
    if "School_Name" in df:
        df["School_Name"] = df["School_Name"].apply(clean_text)
    if "School_Code" in df:
        df["School_Code"] = df["School_Code"].astype(str).str.zfill(3)
    if "Enrollment" in df:
        df["Enrollment"] = pd.to_numeric(df["Enrollment"], errors="coerce").fillna(0).astype(int)
    df = df.drop_duplicates().reset_index(drop=True)
    return df

# --- run cleaning ---
menu_df = pd.read_csv(menu_csv)
pdf_df = pd.read_csv(pdf_csv)
school_df = pd.read_csv(school_csv)

menu_clean = clean_menu(menu_df)
pdf_clean = clean_pdf(pdf_df)
school_clean = clean_schools(school_df)

# --- save outputs ---
menu_clean.to_csv(f"{OUT_DIR}/menu_clean.csv", index=False)
pdf_clean.to_csv(f"{OUT_DIR}/pdf_clean.csv", index=False)
school_clean.to_csv(f"{OUT_DIR}/schools_clean.csv", index=False)

print("✅ Data cleaning complete. Cleaned files saved to:", OUT_DIR)